import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"
import Sidebar from "@/components/Sidebar"
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pivot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className="flex min-h-screen min-w-screen">
            <Sidebar />
            <div className="flex flex-col w-full">
              <Navbar />
              <Toaster />
              {children}
            </div>
          </div>
      </body>
    </html>
  )
  // return (
  //   <html lang="en">
  //   <div className="flex min-h-screen min-w-screen">
  //     <Sidebar />
  //     <Navbar />
  //     <body className={inter.className}>{children}</body>
  //   </div>
  //   </html>
  // );
}
